language: php

php:
  - 5.4
  - 5.5

env:
 - DB=mysql

before_install:
 - composer selfupdate
 - composer install
 - 'wget http://pecl.php.net/get/APCu ; tar -xzf APCu ; sh -c "cd apcu-* && phpize && ./configure  && make && sudo make install && rm -rf ../APCu*" ; echo "extension=apcu.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`'
 - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS blogbeartest;USE blogbeartest;CREATE TABLE IF NOT EXISTS posts (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(50),body TEXT,created DATETIME DEFAULT NULL,modified DATETIME DEFAULT NULL);" -u root; fi
 - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS blogbear;USE blogbear;CREATE TABLE IF NOT EXISTS posts (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(50),body TEXT,created DATETIME DEFAULT NULL,modified DATETIME DEFAULT NULL);" -u root; fi
 - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar
 - pear config-set auto_discover 1
 - pear install pear.phpunit.de/DbUnit

script:
 - phpunit --coverage-text
 - php tests/bin/run.php
 - output=$(php php-cs-fixer.phar fix -v --dry-run --fixers=indentation,linefeed,trailing_spaces,short_tag,visibility,php_closing_tag,braces,extra_empty_lines,include,elseif,eof_ending  .); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;

notifications:
  email: false
